--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/02/2020 13:49:16
-- Server version: 5.5.5-10.1.40-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS ejemplo7_lajota_poo;

CREATE OR REPLACE DATABASE ejemplo7_lajota_poo
	CHARACTER SET latin1
	COLLATE latin1_spanish_ci;

--
-- Set default database
--
USE ejemplo7_lajota_poo;

--
-- Create table `productos`
--
CREATE OR REPLACE TABLE productos (
  id int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(255) DEFAULT NULL,
  foto varchar(255) DEFAULT NULL,
  descripcion varchar(255) DEFAULT NULL,
  precio float DEFAULT NULL,
  oferta tinyint(4) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_spanish_ci;

--
-- Create table `categorias`
--
CREATE OR REPLACE TABLE categorias (
  id int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(255) DEFAULT NULL,
  descripcion varchar(255) DEFAULT NULL,
  foto varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_spanish_ci;

--
-- Create table `relacion`
--
CREATE OR REPLACE TABLE relacion (
  id int(11) NOT NULL AUTO_INCREMENT,
  producto int(11) DEFAULT NULL,
  categoria int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_spanish_ci;

--
-- Create foreign key
--
ALTER TABLE relacion
ADD CONSTRAINT FK_relacion_categorias_id FOREIGN KEY (categoria)
REFERENCES categorias (id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE relacion
ADD CONSTRAINT FK_relacion_productos_id FOREIGN KEY (producto)
REFERENCES productos (id) ON DELETE NO ACTION;

-- 
-- Dumping data for table productos
--
-- Table ejemplo7_lajota_poo.productos does not contain any data (it is empty)

-- 
-- Dumping data for table categorias
--
-- Table ejemplo7_lajota_poo.categorias does not contain any data (it is empty)

-- 
-- Dumping data for table relacion
--
-- Table ejemplo7_lajota_poo.relacion does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;